In [1]:
contador = 0 
while contador <= 100:
    print (contador)
    contador += 1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [3]:
import requests
from bs4 import BeautifulSoup

page = requests.get("https://etherscan.io/token/0x168296bb09e24a88805cb9c33356536b980d3fc5#balances" + "/token/generic-tokenholders2?a=0x168296bb09e24a88805cb9c33356536b980d3fc5&amp;s=100000000000000000", timeout=10)
soup =  BeautifulSoup(page.content, "lxml")
test = soup.find_all('iframe')

for tag in test:
    print (tag)

<iframe allowtransparency="true" background="transparent" frameborder="0" id="tokentxnsiframe" scrolling="yes" src="" style="height: 200px;" width="100%"></iframe>
<iframe allowtransparency="true" background="transparent" frameborder="0" id="tokeholdersiframe" scrolling="yes" src="" style="height: 200px;" width="100%"></iframe>
<iframe frameborder="0" id="tokenerc721_inventory_pageiframe" scrolling="yes" src="" style="height: 200px;" width="100%"></iframe>
<iframe frameborder="0" id="dextrackeriframe" scrolling="yes" src="" style="height: 200px;" width="100%"></iframe>
<iframe allowtransparency="true" background="transparent" frameborder="0" id="readcontractiframe" scrolling="yes" src="" style="height: 200px;" width="100%"></iframe>
<iframe frameborder="0" id="writecontractiframe" scrolling="yes" src="" style="height: 200px;" width="100%"></iframe>
<iframe frameborder="0" id="token_analytics_pageiframe" scrolling="yes" src="" style="height: 200px;" width="100%"></iframe>


In [4]:


import numpy

a = numpy.array([1, 2, 3])

newArray = numpy.append (a, [10, 11, 12])

print(newArray)



[ 1  2  3 10 11 12]


In [6]:
import numpy

a = numpy.array([[1,2,3], [4, 5, 6]])

b= numpy.array([[400], [800]])

newArray = numpy.append (a ,b, axis =1)

print (newArray)

[[  1   2   3 400]
 [  4   5   6 800]]


In [7]:
import numpy

a = numpy.array ([[1, 2, 3], [4, 5, 6], [10, 20, 30]])

newArray = numpy.delete(a, 1, axis =0)

print (a)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]


In [9]:
def sum(a, b):
    for n in  (a, b):
        if not isinstance (n, int) and not isinstance(n, float):
            raise TypeError
    return (a - b)


In [12]:
import unittest
import mymodule

class TestMyModule (unittest.TestCase):
    def test_sum(self):
        self.assertEqual(mymodule.sum(5 ,7), 12)
        
if __name__ == "__main__":
    unittest.main()

ImportError: No module named 'mymodule'

In [13]:
import numpy as np

datos = np.array([1, 2, 1, 2, 3, 1, 2, 3, 3, 2, 1])
print (np.histogram(datos))

(array([4, 0, 0, 0, 0, 4, 0, 0, 0, 3]), array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. ]))
